# Generated by Django 4.2.5 on 2023-10-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Course title')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='course/', verbose_name='Course picture')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Course description')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lesson title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Lesson description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='course/lesson')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Lesson video URL')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
    ]
