# Generated by Django 4.2.5 on 2023-10-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='way_of_payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer')], max_length=10, verbose_name='Way of Payment'),
        ),
    ]
