# Generated by Django 4.2.5 on 2023-10-16 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='course.course', verbose_name='Course'),
        ),
    ]
