# Generated by Django 4.2.5 on 2023-10-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_price_lesson_price_alter_subscription_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
