# Generated by Django 4.2.5 on 2023-10-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_payments_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
    ]
